package vista;

/**
 * Vista del menu de consultas adicionales
 * @author Daniel Vaglio Fallas y Jafet Chavarria Moreno
 * @version Proyecto Programado I
 */
public class MenuConsultasAdicionales extends javax.swing.JFrame {

    public MenuConsultasAdicionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnConsultarClientesOrdenados = new javax.swing.JButton();
        btnConsultarCuentasOrdenadas = new javax.swing.JButton();
        btnConsultarInformacionCliente = new javax.swing.JButton();
        btnConsultarInformacionCuentaParticular = new javax.swing.JButton();
        btnConsultarSaldoActual = new javax.swing.JButton();
        btnConsultarEstadoCuenta = new javax.swing.JButton();
        btnConsultarEstadoCuentaDivisaExtranjera = new javax.swing.JButton();
        btnConsultarEstatusCuenta = new javax.swing.JButton();
        btnConsultarGananciasComisionesTotalizado = new javax.swing.JButton();
        btnConsultarGananciasComisionesCuentaEspecifico = new javax.swing.JButton();
        btnConsultarTipoDeCambio = new javax.swing.JButton();
        btnConsultarSaldoDivisaExtranjera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 102, 204));

        btnVolver.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Consultas adicionales");

        btnConsultarClientesOrdenados.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarClientesOrdenados.setText("Consultar clientes ordenados ascedentenmente");
        btnConsultarClientesOrdenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesOrdenadosActionPerformed(evt);
            }
        });

        btnConsultarCuentasOrdenadas.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarCuentasOrdenadas.setText("Consultar cuentas ordenados descendentemente");
        btnConsultarCuentasOrdenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCuentasOrdenadasActionPerformed(evt);
            }
        });

        btnConsultarInformacionCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarInformacionCliente.setText("Consultar Informacion de un cliente en particular");
        btnConsultarInformacionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarInformacionClienteActionPerformed(evt);
            }
        });

        btnConsultarInformacionCuentaParticular.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarInformacionCuentaParticular.setText("Consultar Informacion de una cuenta en particular");
        btnConsultarInformacionCuentaParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarInformacionCuentaParticularActionPerformed(evt);
            }
        });

        btnConsultarSaldoActual.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarSaldoActual.setText("Consultar Saldo de una Cuenta");
        btnConsultarSaldoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSaldoActualActionPerformed(evt);
            }
        });

        btnConsultarEstadoCuenta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarEstadoCuenta.setText("Consultar Estado de una Cuenta");
        btnConsultarEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadoCuentaActionPerformed(evt);
            }
        });

        btnConsultarEstadoCuentaDivisaExtranjera.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarEstadoCuentaDivisaExtranjera.setText("Consultar Estado de una Cuenta (divisa extranjera)");
        btnConsultarEstadoCuentaDivisaExtranjera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadoCuentaDivisaExtranjeraActionPerformed(evt);
            }
        });

        btnConsultarEstatusCuenta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarEstatusCuenta.setText("Consultar Estatus de una Cuenta");
        btnConsultarEstatusCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstatusCuentaActionPerformed(evt);
            }
        });

        btnConsultarGananciasComisionesTotalizado.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarGananciasComisionesTotalizado.setText("Consultar Ganancias del Banco Producto del Cobro de Comisiones Totalizado");
        btnConsultarGananciasComisionesTotalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGananciasComisionesTotalizadoActionPerformed(evt);
            }
        });

        btnConsultarGananciasComisionesCuentaEspecifico.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarGananciasComisionesCuentaEspecifico.setText("Consultar Ganancias del Banco Producto del Cobro de Comisiones de una Cuenta en Especifico");
        btnConsultarGananciasComisionesCuentaEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGananciasComisionesCuentaEspecificoActionPerformed(evt);
            }
        });

        btnConsultarTipoDeCambio.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarTipoDeCambio.setText("Consultar Tipo de Cambio ");
        btnConsultarTipoDeCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTipoDeCambioActionPerformed(evt);
            }
        });

        btnConsultarSaldoDivisaExtranjera.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnConsultarSaldoDivisaExtranjera.setText("Consultar Saldo de una Cuenta (Divisa Extranjera)");
        btnConsultarSaldoDivisaExtranjera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSaldoDivisaExtranjeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultarGananciasComisionesCuentaEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultarGananciasComisionesTotalizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarTipoDeCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConsultarSaldoActual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuLayout.createSequentialGroup()
                                        .addComponent(btnConsultarClientesOrdenados, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnConsultarCuentasOrdenadas))
                                    .addComponent(btnConsultarSaldoDivisaExtranjera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnConsultarInformacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnConsultarInformacionCuentaParticular)
                                            .addComponent(btnConsultarEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3))
                                    .addComponent(btnConsultarEstadoCuentaDivisaExtranjera, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(135, 135, 135)
                                .addComponent(lblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnConsultarEstatusCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarClientesOrdenados, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarInformacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarCuentasOrdenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarInformacionCuentaParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarSaldoDivisaExtranjera, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarEstadoCuentaDivisaExtranjera, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnConsultarEstatusCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarTipoDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarGananciasComisionesTotalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarGananciasComisionesCuentaEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConsultarClientesOrdenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesOrdenadosActionPerformed

    }//GEN-LAST:event_btnConsultarClientesOrdenadosActionPerformed

    private void btnConsultarCuentasOrdenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCuentasOrdenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarCuentasOrdenadasActionPerformed

    private void btnConsultarInformacionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarInformacionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarInformacionClienteActionPerformed

    private void btnConsultarInformacionCuentaParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarInformacionCuentaParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarInformacionCuentaParticularActionPerformed

    private void btnConsultarSaldoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarSaldoActualActionPerformed

    private void btnConsultarEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEstadoCuentaActionPerformed

    private void btnConsultarEstadoCuentaDivisaExtranjeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadoCuentaDivisaExtranjeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEstadoCuentaDivisaExtranjeraActionPerformed

    private void btnConsultarEstatusCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstatusCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEstatusCuentaActionPerformed

    private void btnConsultarGananciasComisionesTotalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGananciasComisionesTotalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarGananciasComisionesTotalizadoActionPerformed

    private void btnConsultarGananciasComisionesCuentaEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGananciasComisionesCuentaEspecificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarGananciasComisionesCuentaEspecificoActionPerformed

    private void btnConsultarTipoDeCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTipoDeCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarTipoDeCambioActionPerformed

    private void btnConsultarSaldoDivisaExtranjeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSaldoDivisaExtranjeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarSaldoDivisaExtranjeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsultasAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsultasAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsultasAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsultasAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsultasAdicionales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarClientesOrdenados;
    public javax.swing.JButton btnConsultarCuentasOrdenadas;
    public javax.swing.JButton btnConsultarEstadoCuenta;
    public javax.swing.JButton btnConsultarEstadoCuentaDivisaExtranjera;
    public javax.swing.JButton btnConsultarEstatusCuenta;
    public javax.swing.JButton btnConsultarGananciasComisionesCuentaEspecifico;
    public javax.swing.JButton btnConsultarGananciasComisionesTotalizado;
    public javax.swing.JButton btnConsultarInformacionCliente;
    public javax.swing.JButton btnConsultarInformacionCuentaParticular;
    public javax.swing.JButton btnConsultarSaldoActual;
    public javax.swing.JButton btnConsultarSaldoDivisaExtranjera;
    public javax.swing.JButton btnConsultarTipoDeCambio;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
